layout/lablebox/urls.py
from django.urls import path

from lablebox.views import index

app_name="lablebox"

urlpatterns = [
    path("index/", index, name="index"),

]

layout/layout/urls.py
from django.contrib import admin
from django.urls import path, include

#from lablebox.views import index
from vueapp.views import index
from classificator.views import TotalAPIView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', index, name="index"),
    path('api/v1/classificator', TotalAPIView.as_view(), name='my_api')#ClassificatorAPIView.as_view())
]

layout/users/urls.py
from django.urls import path

from users.views import login, registration

app_name="users"

urlpatterns = [
    path("login/", login, name="login"),
    path("registration/", registration, name = "registration")
]

layout/classificator/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class APIGroups(models.Model):
    title = models.CharField(max_length=256)
    code = models.CharField(max_length=256)

    def __str__(self):
        return self.title


class APIClasses(models.Model):
    #parent = models.ForeignKey("APILables", on_delete=models.PROTECT, blank=True)
    title = models.CharField(max_length=256)
    code = models.CharField(max_length=256)
    lables = models.ManyToManyField("APILables", blank=True)
    groups = models.ManyToManyField("APIGroups", blank=True)

    def __str__(self):
        return self.title


class APILables(models.Model):
    title = models.CharField(max_length=256)
    code = models.CharField(max_length=256)
    type = models.CharField(max_length=256, blank=True)
    mask = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.title

layout/lablebox/models.py
from django.db import models

# Create your models here.

layout/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to="users_images", null="True", blank=True)

layout/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "data",
        "placeholder": "Username"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "data",
        "placeholder": "Password"
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "class": "data",
        "placeholder": "Username"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "data",
        "placeholder": "Password"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "data",
        "placeholder": "Confirm Password"
    }))

    class Meta:
        model = User
        fields = ('username', "password1", "password2")

layout/classificator/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from classificator.models import APIClasses, APIGroups, APILables
from .serializers import ClassSerializer, GroupSerializer, LabelSerializer

# Create your views here.

class TotalAPIView(APIView):
    def get(self, request):
        class_result = APIClasses.objects.all()
        groups_result = APIGroups.objects.all()
        labels_result = APILables.objects.all()

        Class_serializer = ClassSerializer(class_result, many=True).data
        Group_serializer = GroupSerializer(groups_result, many=True).data
        Label_serializer = LabelSerializer(labels_result, many=True).data

        data = {
            "groups": Group_serializer,
            "classes": Class_serializer,
            "labels": Label_serializer,
        }
        return Response(data)

# class ClassAPIView(generics.ListAPIView):
#     queryset = APIClasses.objects.all() #, APILables.objects.all(), APIGroups.objects.all()}
#     serializer_class = ClassSerializer


# class GroupsAPIView(generics.ListAPIView):
#     queryset = APIGroups.objects.all()
#     serializer_class = GroupSerializer


# class LabelAPIView(generics.ListAPIView):
#     queryset = APILables.objects.all()
#     serializer_class = LabelSerializer

layout/lablebox/views.py
from django.shortcuts import render

def index(request):
    return render(request, "lablebox/index.html") #"create-vue-app/src/pages/Main.vue")

layout/users/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect
from users.forms import UserLoginForm, UserRegistrationForm
from django.contrib import auth
from django.urls import reverse

def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponsePermanentRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {"form": form}
    return render(request, "users/sign_in.html", context)

def registration(requset):
    if requset.method == "POST":
        form = UserRegistrationForm(data=requset.POST)
        if form.is_valid():
            form.save()
            return HttpResponsePermanentRedirect(reverse('users:login'))
    else:
        form=UserRegistrationForm()
    context = {"form": form}
    return render(requset, "users/registration.html", context)

#def index(request):
#    context = {
#        "title": 'some shit'
#    }
#    return render(request, "users/index.html", context)

layout/lablebox/templates/lablebox/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Prototype of Label Box</title>
      <link rel="stylesheet" href="{%static 'vendor\css\style(2).css'%}">
      <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
   </head>
   <body>
      <header>
         <a href="#" class="logo">Label Box</a>
         <nav>
            <ul class="list">
               <li><a href="#" class="item">Home</a></li>
               <li><div class="item">Project &bigtriangledown;</div>
                  <ul class="subList">
                     <li><div class="item">Open project</div></li>
                     <li><div class="item">Create project</div></li>
                     <li><div class="item">Add images &bigtriangledown;</div>
                        <ul class="subSubList">
                           <li><div class="item">jpeg</div></li>
                           <li><div class="item">png</div></li>
                        </ul>
                     </li>
                  </ul>
               </li>
               <li><div class="item">Annotation &bigtriangledown;</div>
                  <ul class="subList">
                     <li><div class="item">Download annotation</div></li>
                     <li><div class="item">Unload annotation</div></li>
                     <li><div class="item">Save annotation</div></li>
                  </ul>
               </li>
               <li><a href="#" class="item">Account</a></li>
            </ul>
         </nav>
      </header>
      <div class="main">
         <div class="Tools">
            <ul>
               <li>
                  <i class='bx bx-images' ></i>
                  <p>Images</p>
               </li>
               <li>
                  <i class='bx bx-network-chart'></i>
                  <p>Classifier</p>
               </li>
               <li onclick="Download_btn()">
                  <i class='bx bx-export' ></i>
                  <p>Export</p>
               </li>
            </ul>
         </div>
         <div class="content">
            <p id="projectName">***Project name***</p>
            <div class="choose_image">
               <div class="upload_img_box">
                  <i class='bx bxs-image-add' ></i><br>
                  <input type="file" name="selectedImage" id="selectedImage" accept="image/jpeg, image/png">
                  <p>choose Image from folder</p>
               </div>
            </div>
            <canvas id="image_canvas"></canvas>
            <div class="image_holder">
               <button id="remove_img_btn"><i class='bx bxs-message-square-x' ></i></button>
               <img src="" alt="img" id="image">
            </div>
            <button id="clearAll"><span>Reset</span><i class='bx bx-reset' ></i></button>
         </div>
         <div class="Tools">
            <ul>
               <li>
                  <i class='bx bx-search-alt'></i>
                  <p>Search</p>
               </li>
               <li>
                  <i class='bx bxs-droplet-half'></i>
                  <p>Colour</p>
               </li>
               <li>
                  <i class='bx bxs-trash' ></i>
                  <p>Trash</p>
               </li>
            </ul>
         </div>
      </div>
      <script src="{%static 'vendor\js\main.js'%}"></script>
   </body>
</html>

layout/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

layout/users/templates/users/registration.html
{% load static %}
<!--Встроенные теги и фильтры шаблонов в следующем патче уберу-->

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{%static 'vendor\css\style.css'%}">
	</head>
	<body>
		<form class="box" action="{% url 'users:registration' %}" method="post">
			{% csrf_token %}
			<a href="{% url 'users:login'%}">Login</a><br>
			<a href="{% url 'users:registration'%}" style="font-size: 25px; color: #FF7043;">Registration</a>
			<div>
				<label for="{{ form.username.id_for_label }}"></label>
				{{ form.username }}
			</div>
			<!-- <input class="data" type="password" placeholder="Password">
			<input class="data" type="password" placeholder="Confirm Password"> -->
			{{ form.password1 }}
			{{ form.password2 }}
			<input type="submit" value="Login">
		</form>
	</body>
</html>

layout/users/templates/users/sign_in.html
{% load static %}
<!--Встроенные теги и фильтры шаблонов в следующем патче уберу-->

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{% static 'vendor\css\style.css' %}">
	</head>
	<body>
		<form class="box" action="{% url 'users:login' %}" method="post">
			{% csrf_token %}
			<a href="{% url 'users:login'%}" style="font-size: 25px; color: #FF7043;">Login</a><br>
			<a href="{%url 'users:registration'%}" id="registation">Registration</a>
			<div>
				<label for="{{ form.username.id_for_label }}"></label>
				{{ form.username }}
			</div>
				<!-- <input class="data" type="text" placeholder="Username"> -->
				<!-- <input class="data" type="password" placeholder="Password"> -->
			{{ form.password }}
			<input type="submit" value="Login">
		</form>
	</body>
</html>